[build]
target = "../../avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "cargo avr run board uno --baudrate 57600"
# To run in simulator, replace the line above with this:
# runner = "simavr -m atmega328p"

[unstable]
build-std = ["core"]
